-- =============================================================================
-- Migration 068 — trainer_preferences: useLeadName + targetClientGender (Hito 12.2)
-- =============================================================================
--
-- Hito 12.2 (2026-05-20): añade 2 nuevas dimensiones al JSONB `preferences`:
--
--   1. Uso del nombre del lead — el setter decide si dirigirse al lead por su
--      nombre real cuando GHL/ManyChat/YCloud lo traen. Se evalúa en F0 con
--      heurística regex + Haiku fallback en casos ambiguos. Resultado persiste
--      en leads.parsed_name + leads.parsed_name_status (Fase B). Aquí solo
--      definimos los toggles del trainer:
--        - useLeadNameMode: 'auto' (default) | 'always' | 'never'
--          * auto: el setter usa el nombre SOLO si la detección dice "usable"
--          * always: el setter usa el nombre aunque la detección diga "no
--            usable" (asume riesgo, ej: trainers que aceptan handle como nombre)
--          * never: el setter nunca menciona el nombre al lead
--        - leadNameMaxMentions: 0..5 (default 2). Tope de menciones del nombre
--          en toda la conversación. 0 = equivale a 'never'. Aplica solo si
--          useLeadNameMode != 'never'. Enforce best-effort vía markdown del
--          trainer_prefs_v1 en MVP; futuro V19 validador hace strict count.
--
--   2. Público objetivo del trainer + filtro de género opuesto — si el trainer
--      trabaja solo con un género y la detección en F0 sugiere lo contrario, el
--      setter introduce una pregunta de verificación en F1 (no F0) tipo "¿es
--      para ti o para algún familiar/cercano?". El filtro NO descarta el lead,
--      solo confirma para no perder tiempo si es para un tercero opuesto al
--      target. Detección de género: diccionario es-ES + Haiku fallback.
--        - targetClientGender: 'mixed' (default) | 'male' | 'female'
--          * mixed: sin filtro, feature off de facto.
--          * male/female: el setter espera que el lead sea de ese género.
--        - genderVerificationStyle: 'soft' (default) | 'direct'
--          * soft: pregunta integrada al flujo natural en F1 ("por curiosidad,
--            ¿es para ti o para alguien cercano?")
--          * direct: pregunta explícita ("Trabajo solo con [hombres/mujeres],
--            ¿es para ti o para un familiar?")
--
-- IMPORTANTE: esta migration NO añade columnas ni cambia el shape relacional —
-- todo vive dentro del JSONB existente `preferences`. Solo actualiza el COMMENT
-- documental de la columna para reflejar el shape v8. El parser TS
-- (apps/panel/lib/trainer-prefs-serializer.ts:parseTrainerPreferences) tolera
-- defaults para las 4 claves nuevas, así que los tenants legacy siguen
-- funcionando sin tocar su JSONB.
-- =============================================================================

COMMENT ON COLUMN public.trainer_preferences.preferences IS
  'JSONB con toggles tipados del trainer. Schema v8 (Hito 12.2, 2026-05-20). Estilo (estricto): addressingMode tu|usted|mirror_lead, aiMessagesPerTurnMax 1-4. Nombre del lead (best effort): useLeadNameMode auto|always|never, leadNameMaxMentions 0-5. Filtro genero (best effort): targetClientGender mixed|male|female, genderVerificationStyle soft|direct. Emoticonos: emojisEnabled bool, emojiFrequencyPerMessages 1-3, emojiMaxPerConversation 1-8, customEmojis array. Cualificacion: qualificationQuestionsEnabled bool, extraQuestionsBeforeCall 0-2, callProposalMode calendar|form|human_handoff, closingResourceUrl str|null, calendarClosingMessage str|null. Cumplimiento estricto: forbiddenPhrases string[] (0-10). Contacto: trainerName/Email/Phone str|null. Handoff: handoffPersonalizationEnabled bool, handoffMode share_phone|silent|custom_message, handoffCustomTemplate warm|professional|free, handoffCustomMessage str|null. Hito 11: schedulingMode direct|link|null, trainerTimezone IANA|null. Notificaciones: notificationSubscriptions array. ELIMINADAS en Hito 12.1: messageLengthDensity, toneRegister.';
